### ISSUE TITLE
Add href property to navbar links

### ISSUE THREAD

**Issue by adityaraute** [rbjks/rbjks.github.io#1]
Add links to all the navbar elements. You have freedom to decide the domain name for the hrefs.

**Comment by ArvindParekh** [comment]
Hi @adityaraute! May I work on this issue?

**Comment by adityaraute** [comment]
Hi @ArvindParekh , sure. Assigning this to you.

**Comment by ArvindParekh** [comment]
Thanks! Will start working on this!

**Comment by ArvindParekh** [comment]
Also, I found that the image is not displaying. Can I raise and issue for it?

**Comment by adityaraute** [comment]
No that is by design. Let the image be.

**Comment by ArvindParekh** [comment]
Oh alright.

**Comment by adityaraute** [comment]
Closed by #2
