### ISSUE TITLE
[BUG]: Convert Pull Request Template to Issue Form

### ISSUE THREAD

**Issue by adityaraute** [rbjks/rbjks.github.io#105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Issue Templates are in Issue Form formats, but the PR template isn't.

### Expected Behavior

Mimic the Issue Template UI for PR template

### Steps To Reproduce

1. Create a new PR
2. Observe

**Comment by rahulram21** [comment]
Should the PR template be similar to .github/ISSUE_TEMPLATE/feature_report.yml?

**Comment by adityaraute** [comment]
@rahulram21 Yes, pretty much. Questions from the current PR template, but formatting similar to the Issue Template.

Would you like to work on this issue?

**Comment by manoj9896** [comment]
Hi,
Can I work on this issue if it not picked yet?

**Comment by adityaraute** [comment]
Sure @manoj9896 
Assigning it to you

**Comment by adityaraute** [comment]
Hi @manoj9896 

Can you please update on this issue.

**Comment by manoj9896** [comment]
Hi @adityaraute,
As per the github, **Issue forms are not supported for pull requests** ,

**Comment by manoj9896** [comment]
@adityaraute 
But we can create the multiple templates
Approach:
- In .github directory create an another directory PULL_REQUEST_TEMPLATE
- added two templates 
    - bux_fix.md
    - feature_request.md
- create a file pull_request_template.md at root level to select the template 

Now I am facing the issue in mimicking the template from the issue template as they are in .yaml format and PR template are in .md format

**Comment by adityaraute** [comment]
Okay, then how do you suggest we deal with this issue?
If there's no way out, we can close this issue.

**Comment by adityaraute** [comment]
Hi @manoj9896 ,

> As per github, Issue forms are not supported for pull requests ,

I'll close this issue for the above reason.

Thank you for your support over this.
