### ISSUE TITLE
[FEATURE]:  Translate to Hindi link should be visible on mobile on the main page content

### ISSUE THREAD

**Issue by adityaraute** [rbjks/rbjks.github.io#109]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Currently, the translate to Hindi link is inside the collapsed navbar.

### Proposed Solution

To improve the UX for mobile users, this link/option should be visible on the page content itself.
If possible, the website should also remember the settings from previous pages and carry it forward.

### Do you want to work on this issue?

No

**Comment by shivamalk-23** [comment]
i want to work on this project please assign me kindly

**Comment by adityaraute** [comment]
Hey @shivamalk-23 
What's the update on this one?

**Comment by adityaraute** [comment]
Hi @shivamalk-23 

Please update on this issue by the end of May. Else we will have to reassign this issue to someone else.

**Comment by adityaraute** [comment]
Hi @shivamalk-23 ,

I'm reassigning this issue due to no response from you over the comments.

**Comment by kripa-sindhu-007** [comment]
Hi @adityaraute I would like to work on this issue. Could you please assign it to me??

**Comment by adityaraute** [comment]
Assigned @kripa-sindhu-007

**Comment by kripa-sindhu-007** [comment]
@adityaraute I have made the necessary changes can you verify if anything else is required?

**Comment by kripa-sindhu-007** [comment]
@adityaraute This issue is resolved. It's time to remove this from list.
