### ISSUE TITLE
[BUG]: TYPO: Contact page title is activities

### ISSUE THREAD

**Issue by adityaraute** [rbjks/rbjks.github.io#110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The tab title for Contact page is incorrect

### Expected Behavior

Contact page tab title should read Contact

### Steps To Reproduce

1. Click on the Contact Us option in the navbar

**Comment by Gokilp** [comment]
can you assign me

**Comment by Gokilp** [comment]
please checkout my PR

**Comment by adityaraute** [comment]
Will do, thanks.

**Comment by Gokilp** [comment]
Thank you please change review my profile @adityaraute
