### ISSUE TITLE
[FEATURE]: Instead of the normal hamburger with a up to down mobile navbar slider create a better looking slider from right to left in the mobile view of every page

### ISSUE THREAD

**Issue by mohit-bhandari45** [rbjks/rbjks.github.io#113]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Yes The problem is by clicking on the hamburger on mobile screen the icons pop up from the top and it looks very bad.
Instead of that we can make a right to left slider with proper spacing between elements and we can close it by clicking on the same hamburger icon.

### Proposed Solution

The solution is that we should change the css of the mobile navbar and set to absolute with right 0 and also will change the zindex of the hamburger so that it can be visible.

### Screenshots

Before:-
![Screenshot 2024-03-26 214746](https://github.com/rbjks/rbjks.github.io/assets/151373021/dbf90180-ccb1-4a60-a878-4da8ae8bf917)

After:-
![Screenshot 2024-03-26 214838](https://github.com/rbjks/rbjks.github.io/assets/151373021/bdc8f516-9efb-46a3-816c-dec3ef5c27c3)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

I have made a website with the same feature.
It would look very awesome if you add the feature

**Comment by mohit-bhandari45** [comment]
Created a PR with a solution do check it

**Comment by mohit-bhandari45** [comment]
![Screenshot 2024-03-26 214838](https://github.com/rbjks/rbjks.github.io/assets/151373021/a18285b0-9d7f-43ce-a0ec-82d4da9c4966)

Done do let me know how it is?

**Comment by adityaraute** [comment]
Hi @mohit-bhandari45 

Please share an update on the PR of this issue. 
If not received by the end of April, we may have to unassign this issue.

**Comment by mohit-bhandari45** [comment]
created a pr you can check
