### ISSUE TITLE
[FEATURE]: "Activites" page is blank

### ISSUE THREAD

**Issue by Harshilmalhotra** [rbjks/rbjks.github.io#118]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

1. "Activities" page should be renamed to "Our Contributions"
2. Activities page content is missing. 

### Proposed Solution

Activities page just has a link to twitter account. We can insert Tweets as content in our activities page. And it can be arranged in a form of timeline. 

### Do you want to work on this issue?

Yes

**Comment by adityaraute** [comment]
Looks like there is some issue here. The `activities` page is supposed to display an image gallery, not the twitter embed. I'm gonna revisit this issue later. Have assigned it a draft status for now.

**Comment by adityaraute** [comment]
I am gonna close this issue because in favour of #134 
@Harshilmalhotra apologies for the confusion, please feel free to explore other issues on the repo.
