### ISSUE TITLE
[BUG]: Add alts to imagess

### ISSUE THREAD

**Issue by Bashamega** [rbjks/rbjks.github.io#127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I have inspected, i noticed that not all images includes an `alt` .
Which is important for a lot of things including:

- Enable screen readers to read the information about on-page images for the benefit of a person with complete lack of sight, visually impaired, or who is otherwise unable to view the images on the page.
- Greatly improve search engine optimization (SEO) by helping search engines figure out what is actually in the image.
- Allow search engines to better crawl and rank your website.
- Provide context to what an image is displaying, informing search engine crawlers and allowing them to index an image correctly.
- Help users of screen magnification to know what the purpose of the image is.
-

### Steps To Reproduce

1. Open the site.
2. Inspect the image of the man
3. You cant find an alt

### Anything else?

I would love to work on it.

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by adityaraute** [comment]
That's a good spot. I'll assign the issue to you!
