### ISSUE TITLE
[BUG]: Activities page redesign

### ISSUE THREAD

**Issue by adityaraute** [rbjks/rbjks.github.io#134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Does not show the image gallery

### Expected Behavior

Should display the image gallery

### Steps To Reproduce

NA

**Comment by SidharthSreekumar** [comment]
Hi @adityaraute,

I can work on this. Are there any contribution guidelines or implementation suggestions?

**Comment by adityaraute** [comment]
Sorry, this issue is also assigned to me.
You can check whether an issue is assigned or not in the top right section on Desktop View.

**Comment by adityaraute** [comment]
I should have created a PR but I messed up.
Anyways, the issue is fixed by [this commit.](https://github.com/rbjks/rbjks.github.io/commit/c9e7e34f5407c7c0bc5eee0351238e4f34bd4af1)
