### ISSUE TITLE
[FEATURE]: Remove the Twitter widget on the Activities page

### ISSUE THREAD

**Issue by adityaraute** [rbjks/rbjks.github.io#143]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

It doesn't render any info so should be removed.

### Proposed Solution

Remove that entire div and let activities gallery be the only thing visible there.

### Screenshots

BEFORE:
![image](https://github.com/rbjks/rbjks.github.io/assets/43912470/6ed9afa2-e0d3-4b64-86e6-4acce3f344a5)

AFTER:
![image](https://github.com/rbjks/rbjks.github.io/assets/43912470/1fa992b0-e1d3-4ab2-8cf7-fc85ea1e5c14)

### Do you want to work on this issue?

No

**Comment by RohanRam** [comment]
Locate the container which displays the twitter widget by inspecting the source code and comment/remove the div class and its body of the required container.

**Comment by adityaraute** [comment]
Sounds good @RohanRam
I'm guessing you want to be assigned this issue?

**Comment by adityaraute** [comment]
Assigned to you

**Comment by RohanRam** [comment]
Why is this still open

**Comment by adityaraute** [comment]
Oh, you didn't link this issue with the PR. Thanks for noticing. Fixing it now.

**Comment by adityaraute** [comment]
Closed by #144
