### ISSUE TITLE
[FEATURE]: Add contributors' list to this repo.

### ISSUE THREAD

**Issue by Harshh18** [rbjks/rbjks.github.io#149]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

I would like to add contributors' list to this repo as a gesture of gratitude towards them.

### Proposed Solution

I'll make use of contrib.rocks for adding the contributors' list.

### Screenshots

![image](https://github.com/rbjks/rbjks.github.io/assets/100986926/98818ba2-4f2a-4314-90a9-e1b3b0965cc3)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

I'll update this in the readme file, kindly assign this issue to me.

**Comment by adityaraute** [comment]
Every repo has this Contributors section on the right hand side.

![image](https://github.com/rbjks/rbjks.github.io/assets/43912470/82e211b0-7e37-4b31-a30f-ab80990fd868)

So I don't think this change is necessary really.
