### ISSUE TITLE
Looks gross on Mobile devices 

### ISSUE THREAD

**Issue by AlokMahapatra26** [rbjks/rbjks.github.io#20]
We have to make it responsive for all devices , can you assign this task to me

**Comment by adityaraute** [comment]
Hi @AlokMahapatra26 , I'd suggest you take up only the navbar's part and make it more responsive. That way we can split this issue into multiple parts further.

**Comment by AlokMahapatra26** [comment]
Gotcha!!

**Comment by adityaraute** [comment]
No update from you since long @AlokMahapatra26

**Comment by adityaraute** [comment]
Unassigning you from this issue @AlokMahapatra26

**Comment by adityaraute** [comment]
Committed directly to main
