### ISSUE TITLE
Modify Footer

### ISSUE THREAD

**Issue by adityaraute** [rbjks/rbjks.github.io#22]
Make the following changes in the footer, instead of placeholder text

Address

> PO Jassur, Tehsil - Nurpur, District - Kangra, HP, 176201

Phone

> +91 - 9418151074 / 8675300009

Email

> RBJKS.info@gmail.com

Twitter link

> https://twitter.com/a_bsays

**Comment by adityaraute** [comment]
@chiragchhabria2  wanna work on this?

**Comment by chiragchhabria2** [comment]
Sure , would love to! But I am busy today so I'll do it tomorrow.

**Comment by adityaraute** [comment]
Sure thing. Assigning this to you now. Make sure you fetch the latest updates from the repo before making any changes

**Comment by adityaraute** [comment]
Thanks for the PR. Raising another issue to add email and phone icons now.
