### ISSUE TITLE
Replace Instagram in footer with Facebook

### ISSUE THREAD

**Issue by adityaraute** [rbjks/rbjks.github.io#23]
In the footer, instead of Instagram icon, add a facebook icon
Link it to:

> https://www.facebook.com/akil.bakhshi/

**Comment by adityaraute** [comment]
@OkelloSam21 wanna work on this one?

**Comment by adityaraute** [comment]
@mjawaaad what about you?

**Comment by OkelloSam21** [comment]
Im in.You can assign this issue to  me @adityaraute.

**Comment by adityaraute** [comment]
Done
