### ISSUE TITLE
Add phone and email icon in the footer

### ISSUE THREAD

**Issue by adityaraute** [rbjks/rbjks.github.io#27]
Add icons in the footer to the left of the phone number, and the email field.

Makee sure the icon theme is same as the one for social media links. Download svg files in assets folder and use those.

**Comment by shyamtawli** [comment]
Hey @adityaraute can you assign me ? 
I want to work on it

**Comment by adityaraute** [comment]
Done.

**Comment by shyamtawli** [comment]
@adityaraute I think icon will look good in contact us, after instagram and twitter so should I do that or you want after phone number and email it self.

**Comment by adityaraute** [comment]
No, its not useful in contact us. User should see the phone number and email up front. So I'd rather you put it there.

**Comment by adityaraute** [comment]
Closed by #33
