### ISSUE TITLE
Image not responsive on smaller devices

### ISSUE THREAD

**Issue by newdydx** [rbjks/rbjks.github.io#28]
**Image should be responsive on all devices**

**Comment by newdydx** [comment]
@adityaraute can I be assigned to this issue.

**Comment by adityaraute** [comment]
Hi @newdydx , sure. Can I know what your strategy will be to resolve this?

**Comment by newdydx** [comment]
@adityaraute I will make use of CSS using media-queries

**Comment by adityaraute** [comment]
Okay sure

**Comment by newdydx** [comment]
@adityaraute I made the pull request

**Comment by adityaraute** [comment]
Closed by #29
