### ISSUE TITLE
Add a standard Footer with placeholder content

### ISSUE THREAD

**Issue by adityaraute** [rbjks/rbjks.github.io#3]
Add a standard footer that would work for an NGO. It should have elements for contact details, info about the organization, and some social links. Make sure it is only at the end of the document and is visible only on scroll.

**Comment by MaruthiKo** [comment]
Hi I would love to work on this issue

**Comment by adityaraute** [comment]
Okay, great. Assigning this to you. Make sure the footer is responsive - it should look good on desktop as well as mobile.

**Comment by MaruthiKo** [comment]
Okay sure, could you elaborate more on how you would like the footer to look like
What elements are to be included/ what social links are to be included

**Comment by adityaraute** [comment]
@MaruthiKo  Please also check the updated README file for some preferred theme colors.

**Comment by MaruthiKo** [comment]
Okay will look into it
