### ISSUE TITLE
Create issue templates

### ISSUE THREAD

**Issue by adityaraute** [rbjks/rbjks.github.io#34]
Please create some issue templates for the repo. Primarily need bug and enhancement templates.

**Comment by CBID2** [comment]
I’ll give it a shot @adityaraute!

**Comment by CBID2** [comment]
Hey @adityaraute! I found two links to resources that can aid you in creating issue templates for your repo:
1. [Issue and Pull Request Template Generator featuring Cthulhu and Lewis Carroll](https://www.talater.com/open-source-templates/) (This one is like a storybook. It's enjoyable! 😄) 
2. [GitHub's version](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)
Let me know if you find this helpful! 😄  👍🏾

**Comment by adityaraute** [comment]
Umm I thought you were going to create a PR for the templates

**Comment by CBID2** [comment]
> Umm I thought you were going to create a PR for the templates

I was but then I stumbled upon these sources during my search and thought they'd be the best solutions since they're quicker.

**Comment by adityaraute** [comment]
Okay, this is great, thanks.
