### ISSUE TITLE
Responsive Footer

### ISSUE THREAD

**Issue by OkelloSam21** [rbjks/rbjks.github.io#38]

**Comment by OkelloSam21** [comment]
I saw a need of making the footer section responsive on multiple devices

**Comment by adityaraute** [comment]
Hi Okello, yes. The footer needs to be made responsive. Will you be able to do this?

**Comment by OkelloSam21** [comment]
Yes I can Handle this issue

**Comment by adityaraute** [comment]
Okay then assigning it to you

**Comment by OkelloSam21** [comment]
Asign me then
