### ISSUE TITLE
Improvise the Contact page

### ISSUE THREAD

**Issue by Kapoor-0905** [rbjks/rbjks.github.io#39]
**Describe the bug**
The contact page seems to be simple

**To Reproduce**
1. Go to 'contact'
2. See the UI

**Expected behavior**
The address and details should come at the top when screen size is say of mobile. The form must be more beautiful

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Kapoor-0905** [comment]
I would like to solve this.
I request you to assign me the issue

**Comment by Kapoor-0905** [comment]
Hello there,
Can you share the social links of your NGO for the contact page

**Comment by adityaraute** [comment]
They are in the footer

**Comment by Kapoor-0905** [comment]
Only Twitter and facebook links are available 
can you share linkedin and instagram too

**Comment by adityaraute** [comment]
The NGO has only those two.

**Comment by Kapoor-0905** [comment]
Okay

**Comment by adityaraute** [comment]
Hi,

Any update on this?

**Comment by adityaraute** [comment]
Hey what' going on with this issue?
