### ISSUE TITLE
Change the footer of the website

### ISSUE THREAD

**Issue by Kapoor-0905** [rbjks/rbjks.github.io#40]
**Is your feature request related to a problem? Please describe.**
The current foot is way too simple and not much emphasizing. I have better footer ideas.

**Describe the solution you'd like**
I would like to create a new footer with the preferred colors

**Describe alternatives you've considered**

**Additional context**

**Comment by Kapoor-0905** [comment]
I would like to complete this issue 
kindly assign me this issue

**Comment by adityaraute** [comment]
I'd need more info before assigning this issue, as currently I'm happy with the footer.

Can you share any prototype of what ideas you have for it?

**Comment by adityaraute** [comment]
Is this only for mobile view or desktop too?

**Comment by Kapoor-0905** [comment]
It will be responsive so currently it is for desktop and for mobile it will adjust accordingly

**Comment by Kapoor-0905** [comment]
According to me in the current footer
1. The logo of NGO is too small.
2. The font used is not that good.
3. The color of Text and the social logo is not similar which seems odd to me.
4. While changing the dimensions of browser window there is no padding.

That's why I was insisting to have a new footer

**Comment by adityaraute** [comment]
Fine go on.

**Comment by Kapoor-0905** [comment]
Thank you

**Comment by adityaraute** [comment]
Please update on this issue

**Comment by Ayush-sss** [comment]
I want to work on this issue.
@adityaraute please let me work on this issue

**Comment by adityaraute** [comment]
okay I've added you as an assignee

**Comment by adityaraute** [comment]
@Ayush-sss what's the update on this one?

**Comment by adityaraute** [comment]
@Kapoor-0905 Any update from you? You are still an assignee to the issue

**Comment by adityaraute** [comment]
Closing this for another issue to opened soon
