### ISSUE TITLE
Update the Favicon for this website

### ISSUE THREAD

**Issue by tmsagarofficial** [rbjks/rbjks.github.io#43]
**Is your feature request related to a problem? Please describe.**
I would love to bring to your notice that this site currently does not have any favicon and I feel adding the favicon would make it look and feel better

**Describe the solution you'd like**
I would like to use the logo of the website itself as the favicon for this site

**Describe alternatives you've considered**
Or may be we can create a favicon which relates with the said color theme and reference of the original logo

**Additional context**

**Comment by adityaraute** [comment]
Check #19 

Can we use part of this logo as a favicon?

**Comment by tmsagarofficial** [comment]
Yes surely or we can use the existing logo itself as the favicon

**Comment by adityaraute** [comment]
The existing logo is only a placeholder. This new logo is to be used everywhere. Will you be looking to work on this issue yourself?

**Comment by tmsagarofficial** [comment]
Yeah i feel i can work on this with continued discussions ....

**Comment by tmsagarofficial** [comment]
Also pls send me the link or file for that logo which u have referenced in that #19

**Comment by adityaraute** [comment]
You'll find it in assets/images/brand folder. 

Assigning this issue to you

**Comment by tmsagarofficial** [comment]
Hey send me the link of source itself or something like that coz that image river there is a bit blurred out

**Comment by adityaraute** [comment]
Yeah that's the tough part. That's the only image we have. This is the only source, don't have anything else.

**Comment by tmsagarofficial** [comment]
Do u want me to create a new one with high clarity with the same design?

**Comment by adityaraute** [comment]
If you can, that would be immensely helpful.

**Comment by tmsagarofficial** [comment]
Hey, what platform was used to design this logo which u referenced below? Was it like kittl or canvas or something else would greatly help if u could say that so that I can recreate it with higher quality.

> You'll find it in assets/images/brand folder.
> 
> Assigning this issue to you

**Comment by adityaraute** [comment]
I got the file from the NGO. They only have this one file. No idea where it came from so can't help you sorry.

**Comment by cmmutale** [comment]
So... From what I gather from the above thread, there is an image in (images/brand/RBJKS logo.png) that can be used for this. Is there any need for any enhancements to it as of now this is the way it would look: 
![Screenshot](https://github.com/rbjks/rbjks.github.io/assets/64278891/ebf8f9cd-0575-406c-8aa9-4836fe66141c)

This seems adequate?

**Comment by adityaraute** [comment]
@cmmutale I don't see your idea in the screenshot. 
You are right about the image, but we may have to modify it to be used for favicon, such that only the circular part of the logo is visible
![image](https://github.com/rbjks/rbjks.github.io/assets/43912470/3115ced0-8bcd-40c2-89f6-142376002574)

We can use the same idea for the image in the navbar as well.

**Comment by SaiPreethamReddyy** [comment]
![image](https://github.com/rbjks/rbjks.github.io/assets/145526144/3afff5f3-753e-4665-a0de-2387f8dd78a8)
Is this fine ?

**Comment by adityaraute** [comment]
Hi @SaiPreethamReddyy 
This image is a placeholder. The actual image to be used this:


>  ![image](https://private-user-images.githubusercontent.com/43912470/292968738-3115ced0-8bcd-40c2-89f6-142376002574.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3ODkyNTksIm5iZiI6MTcwMzc4ODk1OSwicGF0aCI6Ii80MzkxMjQ3MC8yOTI5Njg3MzgtMzExNWNlZDAtOGJjZC00MGMyLTg5ZjYtMTQyMzc2MDAyNTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDE4NDIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5N2Q5ZTI4ZmUwNTkyMDMwNDcyZmM5YmY1ZGJkZjk4YjFjYmMxZGM3ZDkxZGU5NzhhYWE0ZTlmYTliOTM2MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LDvNMuqjs6Z7W1lU2hFFEwJvNe0zxd-KkenXXdNfOaM)


But this image needs to be cropped a bit to fit the required dimensions of the favicon. 
Does it make sense now?

**Comment by SaiPreethamReddyy** [comment]
The image you have sent is not loading , could you resend it please.

**Comment by adityaraute** [comment]
@SaiPreethamReddyy You can check the file out [here](https://github.com/rbjks/rbjks.github.io/blob/main/assets/images/brand/RBJKS%20logo.jpeg)

**Comment by SaiPreethamReddyy** [comment]
![image](https://github.com/rbjks/rbjks.github.io/assets/145526144/950ea284-8baa-43fc-9996-9eca32614102)
the font in the logo seems to be too light , if this is ok please let me know

**Comment by adityaraute** [comment]
Hi @SaiPreethamReddyy, I agree it is too light. But for now we can proceed with this. Please feel free to raise a PR for the same. Thanks!

**Comment by SaiPreethamReddyy** [comment]
Yeah , Thanks @adityaraute . I have raised PR
