### ISSUE TITLE
Make tabs in the contact us part of the footer open in different tab

### ISSUE THREAD

**Issue by tmsagarofficial** [rbjks/rbjks.github.io#44]
**Describe the bug**
I would like to highlight that the social media links given in the footer need to open in new tab to make the user experience feel better.
In the contact us part
<img width="199" alt="image" src="https://user-images.githubusercontent.com/110724849/229303585-949139db-ad2d-4f77-b564-6c94d8500815.png">

**To Reproduce**
1. Go to the site https://rbjks.github.io/
2. Scroll down till the end of the website
3. See that all the social media links open in the same tab as the same tab where the website was open

**Expected behavior**

**Screenshots**
<img width="199" alt="image" src="https://user-images.githubusercontent.com/110724849/229303592-7f634931-f902-46b6-aa2d-8c26bcfe5419.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Opera 
 - Version -

**Smartphone (please complete the following information):**
 - Device: Redmi
 - OS: MIUI 12
 - BrowserChrome
 - Version -

**Additional context**

**Comment by adityaraute** [comment]
Yes this is a very valid issue.
