### ISSUE TITLE
Add color blocks in README

### ISSUE THREAD

**Issue by adityaraute** [rbjks/rbjks.github.io#5]
In the Preferred Theme Colors section of the README file, please add color blocks so that user can actually see the color mentioned.

If including images, make sure all images have the same dimensions.

**Comment by OkelloSam21** [comment]
@adityaraute 

> In the Preferred Theme Colors section of the README file, please add color blocks so that the user can actually see the color mentioned.
> 
> If including images, make sure all images have the same dimensions.

**Comment by OkelloSam21** [comment]
@ArvindParekh can I work on this?

**Comment by ArvindParekh** [comment]
I'm sorry, there's some misunderstanding. I'm not the repository owner. I suggest you ask the repository owner to allow you to work on the issue.

**Comment by OkelloSam21** [comment]
Ohh sorry

**Comment by adityaraute** [comment]
Hi Okello, I've assigned you the issue.

**Comment by OkelloSam21** [comment]
Fine
