### ISSUE TITLE
Create a JSON-based image gallery

### ISSUE THREAD

**Issue by adityaraute** [rbjks/rbjks.github.io#51]
**Is your feature request related to a problem? Please describe.**
Currently, the image gallery is non-functional

**Describe the solution you'd like**
A grid-styled image gallery with captions that takes information from a JSON file stored on the repo.

**Additional context**
Use sample images and captions for the time-being.

**Comment by adityaraute** [comment]
Hi @OkelloSam21  Please go ahead

**Comment by adityaraute** [comment]
Hi @OkelloSam21  How's the progress on this issue?

**Comment by adityaraute** [comment]
Can you link your fork/branch so I can keep checking and give you suggestions?

**Comment by OkelloSam21** [comment]
sure
________________________________

**Comment by adityaraute** [comment]
Resolved by #56
