### ISSUE TITLE
Incorrect Font Colour on `Contact` page

### ISSUE THREAD

**Issue by adityaraute** [rbjks/rbjks.github.io#63]
**Describe the bug**
Incorrect Font Colour on `Contact` page

**To Reproduce**
1. Go to the main branch
2. Click on 'Contact' on the homepage navbar

**Expected behavior**
Change the colour from black to white on the contact page navbar

**Screenshots**
![image](https://github.com/rbjks/rbjks.github.io/assets/43912470/db7e7635-951c-4811-bca4-32f7fa3ab655)

**Comment by adityaraute** [comment]
@ctrl07 you closed that issue, so you can instead work on this one. This is more specific about the problem we discussed.

**Comment by ctrl07** [comment]
Thanks! Please assign it to me.
