### ISSUE TITLE
Add a flag in Issue Template for issue creator to contribute

### ISSUE THREAD

**Issue by adityaraute** [rbjks/rbjks.github.io#64]
**Is your feature request related to a problem? Please describe.**
Often we don't know when an issue is created if the creator wants to work on it themselves.

**Describe the solution you'd like**
In both the issue template files, create a checkbox to ask if the creator wants to work on that particular issue.

**Additional context**
Would also be better if we can then add a section where they describe the ideal solution to their issue

**Comment by Bashamega** [comment]
Please assign me this issue
