### ISSUE TITLE
Fix the footer in `contact` page

### ISSUE THREAD

**Issue by adityaraute** [rbjks/rbjks.github.io#67]
**Describe the bug**
The footer in the `contact` page is completely ruined

**To Reproduce**
1. Go to the website
2. Click on `Contact` in the navbar
3. Scroll down to the bottom of the page

**Expected behavior**
Footer should mimic the one on Homepage.

**Screenshots**
This is how the contact page footer is
![image](https://github.com/rbjks/rbjks.github.io/assets/43912470/34de399d-1732-43a2-afc3-8d1fd96b1a50)

This is how the Homepage footer is. This should be replicated above.
![image](https://github.com/rbjks/rbjks.github.io/assets/43912470/c1869ce7-eaa9-4b4e-9592-f329257c5886)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Google Chrome

**Comment by cjstyles6** [comment]
@rbjks assign me to this issue

**Comment by advait-zx** [comment]
assign me this issue i will solve the problem!

**Comment by adityaraute** [comment]
Hi @advait-zx ,
This issue has already been assigned to someone. But feel free to contribute to other unassigned issues on the repo.
