### ISSUE TITLE
Contact modal not working

### ISSUE THREAD

**Issue by adityaraute** [rbjks/rbjks.github.io#68]
**Describe the bug**
When I filled the form on the contact modal, it doesn't work

**To Reproduce**
1. Go to the website
2. Click on Contact in the navbar
3. Fill form and click on Submit

**Expected behavior**
The message should be sent to the designated email ID in the backend.

**Screenshots**
![image](https://github.com/rbjks/rbjks.github.io/assets/43912470/3e47283e-86e4-4cdb-a169-2f3f9864740b)

**Comment by Not-Sahil-Raja** [comment]
is there any code related to this form?
sorry i can't find any

**Comment by adityaraute** [comment]
@Not-Sahil-Raja Only the HTML part. No script, if that's what you're asking.

**Comment by SaiPreethamReddyy** [comment]
assign me this issue , i think i can do this .

**Comment by SaiPreethamReddyy** [comment]
![image](https://github.com/rbjks/rbjks.github.io/assets/145526144/c5eea528-ffb1-4286-8071-1e1c0ff1eb3a)

I will be using an SMTP server (SMPJS), and for that, I will need the password associated with the email address

**Comment by adityaraute** [comment]
@SaiPreethamReddyy Let me check this and get back to you.

**Comment by adityaraute** [comment]
Hi @SaiPreethamReddyy ,

We have decided to go with an embedded Google Form instead of an email.

Thanks for your contributions.

**Comment by adityaraute** [comment]
Closing in favour of #96
