### ISSUE TITLE
Fix the colors in the home page text for better readability

### ISSUE THREAD

**Issue by tmsagarofficial** [rbjks/rbjks.github.io#74]
**Describe the bug**
The text on the home page has very little readability; hence, changing the colors might help do the job.

**To Reproduce**
1. Go to https://rbjks.github.io/
2. See that the text on the right of the image is a bit harder to read as the text is blended with the background color.

**Expected behavior**
A clear and readable text.

**Screenshots**
![image](https://github.com/rbjks/rbjks.github.io/assets/110724849/cb8b599f-0753-4dd9-856e-81fd11249bed)

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser Opera - LVL5 (core: 105.0.4970.63)

I would love to work on this please assign this issue to me.

**Comment by agriyakhetarpal** [comment]
Thanks, it would be great to get darker colours. You can use [a WCAG contrast checking tool](https://webaim.org/resources/contrastchecker/) to do this further and for any other places where the text is not readable.

**Comment by adityaraute** [comment]
Actually this has been done as part of #61 and #63 and hence is a duplicate
