### ISSUE TITLE
Make the Bug report template uniform

### ISSUE THREAD

**Issue by tmsagarofficial** [rbjks/rbjks.github.io#75]
**Describe the bug**
I would like to point out that specific parts of the Bug report template can be uniformly represented for better flow in the process of filling the issue template.

**To Reproduce**
1. Go to https://github.com/rbjks/rbjks.github.io
2. Click on the Issues tab, Then New issue
3. Click on Bug Report
4. See an error or missing uniformity under Desktop and Smartphone Category/Sublist.

`Im skipping all the sections below this coz the issue is the about this issue template itself`

![image](https://github.com/rbjks/rbjks.github.io/assets/110724849/36f2f895-4fc4-4665-9b8a-5008537912df)
Under the Smartphone and Desktop the : can be added wherever missing like how they are placed for the Device and Browser.

PS: I would love to work on a fix for this issue pls let me know.

**Comment by agriyakhetarpal** [comment]
Thanks @tmsagarofficial, please feel free to open a PR and fix this – I will assign you to this issue.
