### ISSUE TITLE
Use the logo/favicon on the webpages

### ISSUE THREAD

**Issue by adityaraute** [rbjks/rbjks.github.io#78]
### Discussed in https://github.com/rbjks/rbjks.github.io/discussions/19

<div type='discussions-op-text'>

<sup>Originally posted by **adityaraute** February 26, 2023</sup>
![RBJKS logo](https://user-images.githubusercontent.com/43912470/221432167-6b292985-9a82-49c6-9f65-6f67363a212e.jpeg)

So here's a logo we have for the NGO. I'm not sure how to incorporate this logo well enough. Please suggest.</div>

As an extension of this discussion, we should incorporate this logo on our branding in the webpages - mainly header and footer.

**Comment by letsmailvjkumar** [comment]
You can do like this if you want for logo :
<head>
<link rel="icon" type="image/x-icon" href="/images/favicon.ico">
</head>
same goes with footer.
if not, add img tag and all set..

**Comment by adityaraute** [comment]
Hi @letsmailvjkumar 
Would you like to work on this issue yoruself?

**Comment by Bashamega** [comment]
I would like to work on it

**Comment by adityaraute** [comment]
I'll wait for @letsmailvjkumar to respond before assigning to you

**Comment by adityaraute** [comment]
> I wish to work on this issue!

We already have two people willing to work on the issue. I'd suggest finding a different issue, or raising one yourself. We have a lot to work on, on the website.

**Comment by letsmailvjkumar** [comment]
I would like to work on this issue

**Comment by letsmailvjkumar** [comment]
I would like to work on this issue

**Comment by adityaraute** [comment]
Great. Assigning it to you.
