### ISSUE TITLE
Create two new page files

### ISSUE THREAD

**Issue by adityaraute** [rbjks/rbjks.github.io#8]
Create two new html files.

Contact.html and activities.html.

Both those files should have the navbar same as the one in index.html.

**Comment by adityaraute** [comment]
@rohan-kulkarni-25
Do you wish to work on this?

**Comment by GauravKanwat** [comment]
Hey, I think I can do it. Can you assign me?

**Comment by OkelloSam21** [comment]
Hello I be happy to do more contribution on this project. @adityaraute Can you assign me?

**Comment by adityaraute** [comment]
Hi @OkelloSam21 , this issue is already assigned Gaurav. Perhaps you can search for a new issue?

**Comment by OkelloSam21** [comment]
fine

**Comment by adityaraute** [comment]
Closed by #14
