### ISSUE TITLE
Convert all Issue Templates to Issue Forms

### ISSUE THREAD

**Issue by adityaraute** [rbjks/rbjks.github.io#81]
**Describe the solution you'd like**
An issue form with input and textarea fields, like the one that EddieHub has, [linked here.](https://github.com/EddieHubCommunity/BioDrop/issues/new/choose)

**Additional Context**
The fields would still be the ones we have in our Issue templates, only the formatting will have to match the aforementioned link.

- [ ] Would you like to work on this?

**Comment by Latish705** [comment]
Hello I would like to do this work @adityaraute could you please assign me
