### ISSUE TITLE
fix the navbar of contact page for smaller screen(Mobile screen).

### ISSUE THREAD

**Issue by letsmailvjkumar** [rbjks/rbjks.github.io#84]
**Is your feature request related to a problem? Please describe.**
the contact page is not displayed properly in different screen size, especially for mobile screen.

**Describe the solution you'd like**
Would like to add media query, if added make sure to link it to contact page.

**Describe alternatives you've considered**

**Additional context**

- [x] Would you like to work on this?

**Comment by adityaraute** [comment]
- Hi, this is an important point. I think all pages should have the same navbar code.
Are you noticing this only with the Contact page or with other pages as well?
- Also, I noticed you havent ticked the checkbox for whether you'd like to work on this. Can you please confirm the same again?

**Comment by letsmailvjkumar** [comment]
![Screenshot_2024-01-11-17-46-35-989_com android chrome](https://github.com/rbjks/rbjks.github.io/assets/115359380/e1170865-576f-4bb3-b2af-3219cd4fb83e)
Check this

**Comment by adityaraute** [comment]
Yes, this is with the contact page, and it needs to be fixed. What about other pages like Home and Activities?

**Comment by letsmailvjkumar** [comment]
Home and activities are good.

**Comment by adityaraute** [comment]
Then we must replicate the same HTML and CSS code to this branch. We will have to perhaps make very extensive changes to the `contact.css` file. If you are comfortable with it, let me know and I can assign the issue to you.

**Comment by letsmailvjkumar** [comment]
Yes, please!

**Comment by letsmailvjkumar** [comment]
Now is it fine. 
![127 0 0 1_5500_contact html(Samsung Galaxy A51_71)](https://github.com/rbjks/rbjks.github.io/assets/115359380/41454caf-925a-4ab0-9efa-025b123c7193)
![laptop-ss](https://github.com/rbjks/rbjks.github.io/assets/115359380/fc877781-06f8-4799-83a7-957f68fe662f)
