### ISSUE TITLE
Use theme colors in navbar links

### ISSUE THREAD

**Issue by adityaraute** [rbjks/rbjks.github.io#9]
Currently the navbar is not styled.

Add CSS styling to the navbar and the links. The links should stay the same color before/after click. A slight change onhover is fine.

**Comment by ArvindParekh** [comment]
Hi @adityaraute! I'd be happy to contribute to this project again. 
May I work on this issue?

**Comment by adityaraute** [comment]
Sure @ArvindParekh , adding you as the assignee

**Comment by ArvindParekh** [comment]
Thanks!

**Comment by mjawaaad** [comment]
Hey @adityaraute can i work on this issue?

**Comment by adityaraute** [comment]
Hi @mjawaaad This issue is already assigned to ArvindParekh. Please hit the watch button on this repo, and you can contribute whenever a new issue arises.
