### ISSUE TITLE
[FEATURE]: Add a workflow to declare a release

### ISSUE THREAD

**Issue by adityaraute** [rbjks/rbjks.github.io#91]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

I don't want to make up releases for every push. A workflow will make this easier.

### Proposed Solution

For every push to the `deployment` branch, the workflow should create a release with the proper release tags.

### Do you want to work on this issue?

No

### If "yes" to above, please explain how you would technically implement this

N/A

**Comment by devilsaint99** [comment]
Hi @adityaraute , do you want this workflow to be able to create release only and nothing else?

**Comment by adityaraute** [comment]
Yes, let's start with that. Rest can be added later.

**Comment by devilsaint99** [comment]
how are you going to push changes to `deployment`, is it going to be via a PR always?

**Comment by agriyakhetarpal** [comment]
I think this should be done with a GitHub Release.

**Comment by adityaraute** [comment]
@agriyakhetarpal 

> I think this should be done with a GitHub Release.
Currently, I have to manually create a release. Are you suggesting there is a mechanism to automate releases in GitHub without writing a YAML?

> how are you going to push changes to `deployment`, is it going to be via a PR always?

@devilsaint99 Yes.

**Comment by agriyakhetarpal** [comment]
> Currently, I have to manually create a release. Are you suggesting there is a mechanism to automate releases in GitHub without writing a YAML?

You can semi-automate that process by adding a PR and then pushing a tag that can trigger a release workflow. I don't recommend automating it fully, and writing a YAML file will be an inevitable requiremen in any case

**Comment by adityaraute** [comment]
> I don't recommend automating it fully

Any particular reason

**Comment by agriyakhetarpal** [comment]
> Any particular reason?

Makes it harder to revert breaking. You will need to modify the commit for your tag again and either trigger a new release or delete an older one

**Comment by adityaraute** [comment]
> Makes it harder to revert breaking changes. You will need to modify the commit for your tag again and either trigger a new release or delete an older one

Since we only push to `deployment` when confirmed that all changes are desirable, I think this is fine to proceed with. 
Let's see what the assignee @devilsaint99 comes up with in their PR

**Comment by adityaraute** [comment]
@devilsaint99 Can you confirm if you want to work on this issue? I can assign it to you after your reply.

**Comment by adityaraute** [comment]
Perfect. Assigning it to you.

**Comment by adityaraute** [comment]
@devilsaint99 Could you share an update about this issue?

**Comment by devilsaint99** [comment]
hi the changes are done, which branch should I open PR for

**Comment by adityaraute** [comment]
Closed by #146
