### ISSUE TITLE
[BUG]: Unnecessary link in Issue template

### ISSUE THREAD

**Issue by adityaraute** [rbjks/rbjks.github.io#92]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have an unnecessary link in the `Feature Request` issue template.

![image](https://github.com/rbjks/rbjks.github.io/assets/43912470/0f97aa48-f123-4abd-8cde-1024b0275e84)

### Expected Behavior

Remove this Discord link from the template.

### Steps To Reproduce

Go to Issues 
Create a Feature Request issue
Scroll down to see the dead link

**Comment by Hemant187** [comment]
I didn't see any issue regarding discord linki

**Comment by agriyakhetarpal** [comment]
Yes, this text is extra because we don't have a Discord community, could you remove this in a PR?

**Comment by agriyakhetarpal** [comment]
Closed by #94
