### ISSUE TITLE
[FEATURE]: Add gitpod link to README

### ISSUE THREAD

**Issue by adityaraute** [rbjks/rbjks.github.io#97]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Save the efforts for minor changes

### Proposed Solution

Include a direct link for GitPod development as is done in [this repo.](https://github.com/EddieHubCommunity/EddieHubCommunity.github.io)

### Do you want to work on this issue?

No

**Comment by Bashamega** [comment]
Hello:)
I can work on this issue.
Can you assign me?
