### ISSUE TITLE
[FEATURE]: Improve README

### ISSUE THREAD

**Issue by adityaraute** [rbjks/rbjks.github.io#99]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Currently, the README is not very descriptive about the project.

### Proposed Solution

Design a better README which captures the NGO's purpose and mission.

### Do you want to work on this issue?

No

**Comment by iemafzalhassan** [comment]
### Hey @adityaraute 

<h5>I would really love 😇 to work on this website.</h5>
<h6>Could you please describe the functionality and use case of the website, as well as the mission of The NGO, in more descriptive way, It would help to restructure the Readme page. </h6>
<br>



###### ConnectWithMe_For_More_Talks.
[Mail](iemafzalhassan@gmail.com)
[twitter](www.twitter.com/iemafzalhassan/)

**Comment by adityaraute** [comment]
Assigning the issue to you. 
I'll try to get the information.

**Comment by iemafzalhassan** [comment]
#### @adityaraute For sure, please provide me details ASAP so i could get into it.

**Comment by adityaraute** [comment]
The mission:

> Ranjeet Bakhshi Jan Kalyan Sabha is an NGO, working in the tough terrains of Himachal Pradesh, to ensure that the underprivileged get a voice.'

Very succinct.

The purpose of the website can be:

> 'To communicate the activities taken up by RBJKS, and offer a contact point for donors as well as beneficiaries.'

Feel free to elaborate on the purpose part with your own take or GenAI as well.

**Comment by adityaraute** [comment]
@iemafzalhassan What's the update here?

**Comment by adityaraute** [comment]
Hi @iemafzalhassan ,

Please update on this issue by the end of May. Else we will have to reassign this issue to someone else.

**Comment by iemafzalhassan** [comment]
Sorry @adityaraute, I didn't get the notification of the project. Today onward i'm working on the project soon will update with it.

**Comment by iemafzalhassan** [comment]
**Hi @adityaraute**
Can you please share social media profile's of the NGO, so that i can pin it in the contact us section.

**Comment by adityaraute** [comment]
Sure @iemafzalhassan 

Twitter: https://twitter.com/a_bsays?lang=en
Facebook: https://www.facebook.com/akil.bakhshi/

That's all we have, the NGO Founder's social media accounts.

**Comment by iemafzalhassan** [comment]
Thnkew so much @adityaraute

**Comment by iemafzalhassan** [comment]
Hey @adityaraute 
Kindly merge the pull request.

**Comment by adityaraute** [comment]
@iemafzalhassan Please refrain from persistent messages and tags. Maintainers will respond once they get a chance to check the notifications.

**Comment by adityaraute** [comment]
Closed by #141
